import{a as w,S as v,i as a}from"./assets/vendor-C1DvvBV_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&u(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const S="57671668-b0fb5fa9413307bc5c891a87a";async function f(s,e=1){return(await w("https://pixabay.com/api/",{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".js-btn"),q=new v(".gallery-link",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function p(s){const e=s.map(r=>`
<li class="gallery-item">
<a class="gallery-link" href="${r.largeImageURL}">
<img class="gallery-image"
src="${r.webformatURL}"
alt="${r.tags}"/></a>
<div class="info-box">
<p class="info">Likes - ${r.likes}</p>
<p class="info">Views - ${r.views}</p>
<p class="info">Comments - ${r.comments}</p>
<p class="info">Downloads - ${r.downloads}</p>
</div>
</li>`).join("");y.insertAdjacentHTML("beforeend",e),q.refresh()}function P(){y.innerHTML=""}function g(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function b(){m.classList.remove("hidden")}function c(){m.classList.add("hidden")}const E=document.querySelector(".form"),M=document.querySelector('input[type="text"]'),$=document.querySelector(".js-btn");$.addEventListener("click",O);let l=1,i="",n=0;E.addEventListener("submit",x);async function x(s){if(s.preventDefault(),i=M.value.trim().toLowerCase(),!!i){l=1,n=0,g(),c(),P();try{const e=await f(i,l);e.hits.length>0?(p(e.hits),n=e.hits.length,n<e.totalHits?b():(c(),a.info({message:"We're sorry, but you've reached the end of search results."}))):a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}catch{a.error({title:"Error",message:"Please try again!"})}finally{L()}}}async function O(){l+=1,c(),g();try{const s=await f(i,l);p(s.hits),n+=s.hits.length,n>=s.totalHits?(c(),a.info({message:"We're sorry, but you've reached the end of search results."})):b();const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({left:0,top:r*2,behavior:"smooth"})}}catch{a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}finally{L()}}
//# sourceMappingURL=index.js.map
